/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppCats {
    }
    interface AppGallery {
    }
    interface AppHome {
    }
    interface AppKittens {
    }
    interface AppRoot {
    }
    interface CatdivComponent {
        "catName": string;
        "catText": string;
        "colorTheme": 'row-bg-dark' | 'row-bg-light';
        "imgPaths": Array<string>;
        "orientation": 'left' | 'right';
    }
    interface ContactComponent {
    }
    interface ParallaxComponent {
        "imageUrl": string;
        "speed": number;
    }
}
declare global {
    interface HTMLAppCatsElement extends Components.AppCats, HTMLStencilElement {
    }
    var HTMLAppCatsElement: {
        prototype: HTMLAppCatsElement;
        new (): HTMLAppCatsElement;
    };
    interface HTMLAppGalleryElement extends Components.AppGallery, HTMLStencilElement {
    }
    var HTMLAppGalleryElement: {
        prototype: HTMLAppGalleryElement;
        new (): HTMLAppGalleryElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppKittensElement extends Components.AppKittens, HTMLStencilElement {
    }
    var HTMLAppKittensElement: {
        prototype: HTMLAppKittensElement;
        new (): HTMLAppKittensElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCatdivComponentElement extends Components.CatdivComponent, HTMLStencilElement {
    }
    var HTMLCatdivComponentElement: {
        prototype: HTMLCatdivComponentElement;
        new (): HTMLCatdivComponentElement;
    };
    interface HTMLContactComponentElement extends Components.ContactComponent, HTMLStencilElement {
    }
    var HTMLContactComponentElement: {
        prototype: HTMLContactComponentElement;
        new (): HTMLContactComponentElement;
    };
    interface HTMLParallaxComponentElement extends Components.ParallaxComponent, HTMLStencilElement {
    }
    var HTMLParallaxComponentElement: {
        prototype: HTMLParallaxComponentElement;
        new (): HTMLParallaxComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-cats": HTMLAppCatsElement;
        "app-gallery": HTMLAppGalleryElement;
        "app-home": HTMLAppHomeElement;
        "app-kittens": HTMLAppKittensElement;
        "app-root": HTMLAppRootElement;
        "catdiv-component": HTMLCatdivComponentElement;
        "contact-component": HTMLContactComponentElement;
        "parallax-component": HTMLParallaxComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppCats {
    }
    interface AppGallery {
    }
    interface AppHome {
    }
    interface AppKittens {
    }
    interface AppRoot {
    }
    interface CatdivComponent {
        "catName"?: string;
        "catText"?: string;
        "colorTheme"?: 'row-bg-dark' | 'row-bg-light';
        "imgPaths"?: Array<string>;
        "orientation"?: 'left' | 'right';
    }
    interface ContactComponent {
    }
    interface ParallaxComponent {
        "imageUrl"?: string;
        "speed"?: number;
    }
    interface IntrinsicElements {
        "app-cats": AppCats;
        "app-gallery": AppGallery;
        "app-home": AppHome;
        "app-kittens": AppKittens;
        "app-root": AppRoot;
        "catdiv-component": CatdivComponent;
        "contact-component": ContactComponent;
        "parallax-component": ParallaxComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-cats": LocalJSX.AppCats & JSXBase.HTMLAttributes<HTMLAppCatsElement>;
            "app-gallery": LocalJSX.AppGallery & JSXBase.HTMLAttributes<HTMLAppGalleryElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-kittens": LocalJSX.AppKittens & JSXBase.HTMLAttributes<HTMLAppKittensElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "catdiv-component": LocalJSX.CatdivComponent & JSXBase.HTMLAttributes<HTMLCatdivComponentElement>;
            "contact-component": LocalJSX.ContactComponent & JSXBase.HTMLAttributes<HTMLContactComponentElement>;
            "parallax-component": LocalJSX.ParallaxComponent & JSXBase.HTMLAttributes<HTMLParallaxComponentElement>;
        }
    }
}
