/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
export namespace Components {
    interface AppGallery {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface ContactComponent {
    }
    interface ParallaxComponent {
        "imageUrl": string;
        "speed": number;
    }
}
declare global {
    interface HTMLAppGalleryElement extends Components.AppGallery, HTMLStencilElement {
    }
    var HTMLAppGalleryElement: {
        prototype: HTMLAppGalleryElement;
        new (): HTMLAppGalleryElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLContactComponentElement extends Components.ContactComponent, HTMLStencilElement {
    }
    var HTMLContactComponentElement: {
        prototype: HTMLContactComponentElement;
        new (): HTMLContactComponentElement;
    };
    interface HTMLParallaxComponentElement extends Components.ParallaxComponent, HTMLStencilElement {
    }
    var HTMLParallaxComponentElement: {
        prototype: HTMLParallaxComponentElement;
        new (): HTMLParallaxComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-gallery": HTMLAppGalleryElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "contact-component": HTMLContactComponentElement;
        "parallax-component": HTMLParallaxComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppGallery {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface ContactComponent {
    }
    interface ParallaxComponent {
        "imageUrl"?: string;
        "speed"?: number;
    }
    interface IntrinsicElements {
        "app-gallery": AppGallery;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "contact-component": ContactComponent;
        "parallax-component": ParallaxComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-gallery": LocalJSX.AppGallery & JSXBase.HTMLAttributes<HTMLAppGalleryElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "contact-component": LocalJSX.ContactComponent & JSXBase.HTMLAttributes<HTMLContactComponentElement>;
            "parallax-component": LocalJSX.ParallaxComponent & JSXBase.HTMLAttributes<HTMLParallaxComponentElement>;
        }
    }
}
